In [9]:
# Define multi-index for all DataFrames
index = pd.MultiIndex.from_tuples([
    (0, 0), (0, 1), (0, 2), (0, 3), (0, 4),
    (2, 0), (2, 1), (2, 2), (2, 3), (2, 4),
    (3, 0), (3, 1), (3, 2), (3, 3), (3, 4),
    (4, 0), (4, 1), (4, 2), (4, 3), (4, 4),
    (5, 0), (5, 1), (5, 2), (5, 3), (5, 4),
    (6, 0), (6, 1), (6, 2), (6, 3), (6, 4),
    (8, 0), (8, 1), (8, 2), (8, 3), (8, 4),
    (9, 0), (9, 1), (9, 2), (9, 3), (9, 4)
], names=["N", "id"])

# Random data for df_tracks
data_tracks = {
    'pt': np.random.uniform(50, 150, size=len(index)),  # Random pt values between 50 and 150
    'eta': np.random.uniform(-2.5, 2.5, size=len(index)),  # Random eta values between -2.5 and 2.5
    'phi': np.random.uniform(0, 6*np.pi, size=len(index))  # Random phi values between 0 and 6π
}

# Random data for df_towers
data_towers = {
    'pt': np.random.uniform(10, 100, size=len(index)),  # Random pt values between 10 and 100
    'eta': np.random.uniform(-5, 5, size=len(index)),  # Random eta values between -5 and 5
    'phi': np.random.uniform(0, 6*np.pi, size=len(index))  # Random phi values between 0 and 6π
}

# Random data for df_muons
data_muons = {
    'pt': np.random.uniform(20, 200, size=len(index)),  # Random pt values between 20 and 200
    'eta': np.random.uniform(-3, 3, size=len(index)),  # Random eta values between -3 and 3
    'phi': np.random.uniform(0, 6*np.pi, size=len(index))  # Random phi values between 0 and 6π
}

# Convert the dictionaries into DataFrames with the multi-index
df_tracks = pd.DataFrame(data_tracks, index=index)
df_towers = pd.DataFrame(data_towers, index=index)
df_muons = pd.DataFrame(data_muons, index=index)

df_towers = df_tracks.rename(columns={'pt': 'et'})
# Display the three DataFrames
#print("df_tracks:")
#print(df_tracks)
print("\ndf_towers:")
print(df_towers)
#print("\ndf_muons:")
#print(df_muons)



df_towers:
              et       eta        phi
N id                                 
0 0   104.682943  1.426934  13.695087
  1   140.207781  1.859045  16.216658
  2   105.637484 -0.630836  15.628167
  3   107.816531 -1.649673  13.549230
  4   135.011422 -1.463851   9.555138
2 0   112.369438 -1.878465   7.149635
  1    93.468804  1.464999  15.217746
  2    60.649527 -1.386747   2.302001
  3    86.030091  0.456226   8.401883
  4    98.049943 -1.565667  14.462586
3 0   128.043211 -0.049514   8.108045
  1   102.433634  0.779384  13.487590
  2   126.919239 -1.412416  14.933579
  3    58.233015 -1.719545   4.722941
  4   122.101057  1.964555  18.773673
4 0   133.165502  2.477529   1.209542
  1    84.866542  0.586608   6.195403
  2   120.371251 -0.045364  11.087078
  3    74.870909  1.770904   9.257776
  4    88.616633 -1.361055  14.665964
5 0   147.562944 -2.378325   1.578602
  1   127.561835 -0.591388   9.189147
  2    72.589274  0.889577   1.597385
  3    51.198379 -2.098360  12.766385


In [10]:
import pandas as pd
import numpy as np

# Define multi-index for df_tracks
index = pd.MultiIndex.from_tuples([
    (0, 0), (0, 1), (0, 2), (0, 3), (0, 4),
    (2, 0), (2, 1), (2, 2), (2, 3), (2, 4),
    (3, 0), (3, 1), (3, 2), (3, 3), (3, 4),
    (4, 0), (4, 1), (4, 2), (4, 3), (4, 4),
    (5, 0), (5, 1), (5, 2), (5, 3), (5, 4),
    (6, 0), (6, 1), (6, 2), (6, 3), (6, 4),
    (8, 0), (8, 1), (8, 2), (8, 3), (8, 4),
    (9, 0), (9, 1), (9, 2), (9, 3), (9, 4)
], names=["N", "id"])

# Random data for df_tracks
data_tracks = {
    'pt': np.random.uniform(50, 150, size=len(index)),  # Random pt values between 50 and 150
    'eta': np.random.uniform(-2.5, 2.5, size=len(index)),  # Random eta values between -2.5 and 2.5
    'phi': np.random.uniform(0, 6*np.pi, size=len(index))  # Random phi values between 0 and 6π
}

# Create df_tracks DataFrame
df_tracks = pd.DataFrame(data_tracks, index=index)

# Adding a new column 'pdg'
# First third will be 13, second third will be -13, rest will be random integers
n_rows = len(df_tracks)
pdg_values = np.concatenate([
    np.full(n_rows // 3, 13),  # Assign value 13 to the first third
    np.full(n_rows // 3, -13),  # Assign value -13 to the second third
    np.random.randint(-1000, 1000, size=n_rows - 2*(n_rows // 3))  # Assign random integers to the rest
])

# Shuffle the pdg values to ensure randomness
np.random.shuffle(pdg_values)

# Assign the 'pdg' column to df_tracks
df_tracks['pdg'] = pdg_values

# Display the updated df_tracks DataFrame
print(df_tracks)


              pt       eta        phi  pdg
N id                                      
0 0   136.761966  1.766624  12.117329   13
  1   136.250227  1.210921  12.804614   -2
  2   102.253775 -2.467204  16.979561   13
  3   142.175869 -1.700189   5.444169 -751
  4   138.879990  1.235018   3.740970   13
2 0    76.941202  1.164903  15.259896   13
  1    66.855966  0.730979  13.873195  -13
  2   131.609828  2.225264  16.537996   13
  3   135.924617  2.070747   0.745679 -909
  4    73.537961 -0.319763  11.779212   13
3 0    88.734773 -0.764578   4.358207   13
  1   101.666815  1.837203  17.196644  -13
  2    82.205296 -2.301317  10.282917  765
  3    88.922247 -1.122461   3.254407  772
  4   137.471446  2.442374   9.745407  -13
4 0   141.696090 -1.072412  16.517150   13
  1    89.998560  1.699910  13.798962 -727
  2    52.389034  2.396923  14.725090  -13
  3   139.491373 -2.112634  14.712851  -98
  4   141.471563 -0.280975   9.054059   13
5 0    56.227568  2.426985  16.372093   13
  1    88.1

In [60]:
def deltaRcalculation(event_muon, event_track, event_tower):
    '''
    Funtion that calculates 2 delta R: between first input (muon dataframe) and second input (tracks dataframe)
    and between first input and third input(towers dataframe). 
    There is 2 output: deltaR(muon, tracks) and deltaR(muon, towers) 
    '''
    muon_phi = event_muon['phi'].values
    muon_eta = event_muon['eta'].values

    if event_track is not None:
        # Handle the case when event_track is provided
        #print("Using event_track for calculation.")
         # Use event_track variables
        track_phi = event_track['phi'].values
        track_eta = event_track['eta'].values

        # Calculate Δphi and Δη using numpy broadcasting (for muons and tracks)
        # We substract matrix elements:
        # say muon_phi = (1 , 2) and track_phi = (3, 4)
        # then np.subtract.outer(muon_phi, track_phi) gives [(-2, -3),
        #                                                   (-1, -2)] 
        # Therefore, we successfully have [(phiMu1Track1, phiMu1Track2),
        #                                  (phiMu2Track1, phiMu2Track2)] 
        delta_phi_tracks = np.subtract.outer(muon_phi, track_phi)
        delta_eta_tracks = np.subtract.outer(muon_eta, track_eta)

        # Calculate ΔR for all muon-track pairs
        delta_r_tracks = np.sqrt(delta_phi_tracks**2 + delta_eta_tracks**2)
        #print("ΔR for muon-track pairs:\n", delta_r_tracks)
  
    if event_tower is not None:
        # Handle the case when event_tower is provided
        #print("Using event_tower for calculation.")
        tower_phi = event_tower['phi'].values
        tower_eta = event_tower['eta'].values

        # Calculate Δphi and Δη using numpy broadcasting (for muons and towers)
        delta_phi_towers = np.subtract.outer(muon_phi, tower_phi)
        delta_eta_towers = np.subtract.outer(muon_eta, tower_eta)

        # Calculate ΔR for all muon-tower pairs
        delta_r_towers = np.sqrt(delta_phi_towers**2 + delta_eta_towers**2)
        #print("ΔR for muon-tower pairs:\n", delta_r_towers)
    
     # Return a tuple with both delta_r_tracks and delta_r_towers if both are defined
    if event_track is not None and event_tower is not None:
        return delta_r_tracks, delta_r_towers

    # If only one is defined, return that, otherwise return None for both
    return delta_r_tracks if event_track is not None else None, \
           delta_r_towers if event_tower is not None else None

def cone_isolation(track_pt, tower_et, muon_pt, track_pdg, delta_r_tracks, delta_r_towers, delta_r_max= 5, pt_min = 0.5):

    '''
    cone_isolation receives data from a single event and calculates the ratio of[ p_T cone20 / p_T muon ] for tracks and 
    [e_T cone 20 / p_T muon] for towers. These two values are the output.
    '''
    # Determine if there are no leptons within the ΔR max condition

    #print("Printing delta_r_towers")
    #print(delta_r_towers)
    if delta_r_tracks is not None:

        # Apply the ΔR max condition for tracks
        # within_cone_tracks gives a matrix of trues and falses depending on the condition
        within_cone_tracks = (delta_r_tracks < delta_r_max)

        #print("within_cone_tracks")
        #print(within_cone_tracks)

        # Apply the pT min condition to the tracks, setting tracks below pt_min to 0
        # say track_pt = (1,2,3,4,5) and pt_min = 3 then result is (0, 0, 0, 4, 5)
        track_pt_filtered = np.where(track_pt > pt_min, track_pt, 0)

        track_pt_filtered = np.array(track_pt_filtered)

        #print("track_pt_filtered")
        #print(track_pt_filtered)

        # Convert within_cone_tracks to an integer mask (1 for True, 0 for False)
        within_cone_tracks_int = within_cone_tracks.astype(int)

        print("within_cone_tracks_int")
        print(within_cone_tracks_int)

        #print("within_cone_tracks_int")
        #print(within_cone_tracks_int)

        # Multiply the track pT values by the within-cone condition to filter out tracks outside the cone
        # Now, trackfiltered has only the PT information of the tracks that satisfy the condition > pt_min and are within the cone
        track_filtered = within_cone_tracks_int * track_pt_filtered

        print("track_filtered antes de evitar la doble cuenta")
        print(track_filtered)
        # We do not consider in the analysis the same muon
        #track_pdg_mask considera solo los casos dentro del arreglo que tienen muon o antimuon
        # a los que tienen muon los caracteriza con 1 y los que no tienen con None
        track_pdg_array = np.array(track_pdg)
        track_pdg_mask = np.where((track_pdg_array == 13) | (track_pdg_array == -13), 1, 0)
        
        print("track_pdg_array")
        print(track_pdg_array)

        print("track_pdg_mask")
        print(track_pdg_mask)


        # pdg_within_mask is a mask where only the tracks within the cone that have |id|= 13 have 1. others have 0

        #tendremos una matriz donde solo se considera los tower que son muones
        pdg_within_mask = np.array(within_cone_tracks_int) * track_pdg_mask

        pdg_within_mask[pdg_within_mask == 0] = 1e16
        
        print("pdg_within_mask")
        print(pdg_within_mask)

        #print("delta_r_tracks")
        #print(delta_r_tracks)

        # delta_r_filtered will return a matrix containing only the delta_r_tracks of the muon with tracks with id =13 
        delta_r_filtered = np.array(delta_r_tracks) * pdg_within_mask #We use the element multiplication
        
        print("delta_r_filtered")
        print(delta_r_filtered)

        # Replace zeros with np.inf temporarily to avoid selecting as minimum the 0 from the mask
        if np.any(np.all(delta_r_filtered == 0, axis=1)):
            # Encontramos la fila donde todo suma cero
            #esta no tiene sentido pues alli se tendra que el muon no dejo un track lo cual no es posible
            #por ello se manda un mensaje de error
            zero_rows = np.where(np.all(delta_r_filtered == 0, axis=1))[0]
            print(f"Error: Row(s) {zero_rows} contain only zeros. Aborting operation.")
        else:
            # Replace zeros with np.inf temporarily to avoid selecting them as minimum
            mod_deltar_filtered = np.where(delta_r_filtered > 7, np.inf, delta_r_filtered)
             # Find the index of the minimum value in each row


            print("mod_deltar_filtered")
            print(mod_deltar_filtered)
           
            min_deltar = np.argmin(mod_deltar_filtered, axis=1)

            print("min_deltar")
            print(min_deltar)

            min_deltar_row = np.arange(min_deltar.shape[0])  # Generate an array of row indices [0, 1, 2]

            print("min_deltar_row")
            print(min_deltar_row)

            track_filtered[min_deltar_row, min_deltar] = 0.0  # Set the corresponding elements to 0.0

            print("track_filtered")
            print(track_filtered)



        #print("track_filtered")
        #print(track_filtered)

        # Calculate the sum of pT of tracks within the cone for each muon
        # Here we have an array of the sum of PT of every track satisfying the conditions 
        # (pt1_track1+pt1_track2[related to mu1], pt2_track1+pt2_track2+pt2_track3[related to mu2], pt3_track1[related to mu3], etc)
        # This corresponds to p_T cone20 from 2012.00578
        sum_pt_within_cone_tracks = np.sum(track_filtered, axis=1)

        #print("sum_pt_within_cone_tracks")
        #print(sum_pt_within_cone_tracks)

        # Calculate the isolation ratio for each muon based on tracks
        # p_T cone20 / muon_pt
        isolation_ratio_tracks = sum_pt_within_cone_tracks / muon_pt

        #print("isolation_ratio_tracks")
        #print(isolation_ratio_tracks)


        
    if delta_r_towers is not None:

        # Apply the ΔR max condition
        within_cone_towers = (delta_r_towers < delta_r_max)

        # print("within_cone_towers")
        # print(within_cone_towers)

        # print("tower_et before filter")
        # print(tower_et)
        
        # Apply the ET min condition to the towers
        #We have no minimum condition, so we use et > 0
        tower_et_filtered = np.where(tower_et > 0.0, tower_et, 0)

        tower_et_filtered = np.array(tower_et_filtered)

        # print("tower_et_filtered")
        # print(tower_et_filtered)

        within_cone_towers_int = within_cone_towers.astype(int)

        # print("within_cone_towers_int")

        # print(within_cone_towers_int)

        tower_filtered = within_cone_towers_int*tower_et_filtered

        # Calculate the sum of ET of towers within the cone for each muon
       
        # partimos del a mascara que podemos observar que se transforma en 1 si es true y 0 si es false
        # eso nos permite solo considerar los pt de las particulas dentro del cono y si estan fuera no sumar
        # entonces definimos el vector tower_et_filtered que multiplicara toda la columna
        #  t1 t2                                   t1 t2           
        #u1 T T       ----> se transforma a     u1    1 1    ----> 2 +5 = 7
        #t2 F F                                 u2    0 0    ----> 0
        #                                      (et1= 2 et2 =5) multiplicamos esto por la columna

        # ahora en caso et por ejemplo sea menor a el et min entonces lo mandamos a cero para que asi no contribuya
        #  t1 t2                                   t1 t2           
        #u1 T T       ----> se transforma a     u1    1 1    ----> 0 +5 = 5
        #t2 F F                                 u2    0 0    ----> 0
        #                                      (et1= 0 t2 =5)
        #ceste es un caso donde t1 y t2 estan dentro del cono de u1

        # print("tower_filtered")
        # print(tower_filtered)

        sum_et_within_cone_towers = np.sum(tower_filtered, axis=1)

        # print("sum_et_within_cone_towers")
        # print(sum_et_within_cone_towers)

        # Calculate the isolation ratio for each muon
        # print("muon_pt")
        # print(muon_pt)

        isolation_ratio_towers = sum_et_within_cone_towers/muon_pt
    
    if( (delta_r_tracks is not None) and (delta_r_towers is not None)):
        return isolation_ratio_tracks, isolation_ratio_towers

    # If only one is defined, return that, otherwise return None for both
    if((delta_r_tracks is not None) and (delta_r_towers is None)):
        return isolation_ratio_tracks, None
    
    if((delta_r_tracks is None) and (delta_r_towers is not None)): 
        return None, isolation_ratio_towers

    #return isolation_ratio_tracks, isolation_ratio_towers


In [61]:
def muon_isolation(df_muons, df_tracks, df_towers, pt_ratio_max=0.16):


    #0 significa que no es un jet impostor, 1 significa que si lo es
   
    for ix in df_muons.index.get_level_values(0).unique()[:]:
        event_muon = df_muons.loc[ix]

        #print("Jets")
        #print(event_muon)
        #print("ix", ix)

        try:
            event_track = df_tracks.loc[ix]

            try:
                #Tenemos tanto Tracks como Towers
                event_tower = df_towers.loc[ix]
                print(f"Evento que tiene track y tower: '{ix}'")
                
                #print(event_track)
                delta_r_tracks, delta_r_towers = deltaRcalculation(event_muon, event_track, event_tower)

                #print("delta_r_tracks")
                #print(delta_r_tracks)

                print("delta_r_tracks")
                print(delta_r_tracks)

                track_pt = event_track['pt'].values
                tower_et = event_tower['et'].values
                muon_pt = event_muon['pt'].values
                track_pdg = event_track['pdg'].values
                
                isolation_ratio_tracks, isolation_ratio_towers = \
                cone_isolation(track_pt, tower_et, muon_pt, track_pdg, delta_r_tracks, delta_r_towers)

                print("isolation_ratio_tracks")
                print(isolation_ratio_tracks)

                print("isolation_ratio_towers")
                print(isolation_ratio_towers)
                
                #[ p_T cone20 / p_T muon ] + 0.4*[e_T cone 20 / p_T muon] 
                isolation_ratio = isolation_ratio_tracks + 0.4 * isolation_ratio_towers

                #print("isolation_ratio")
                print(isolation_ratio)

                # Determine if each muon is isolated based on the isolation ratio
                # If isolation_ratio < 0.16 then the muon is isolated
                # isolated_muon_mask is an array of trues and falses depending if is isolated or not
                isolated_muon_mask = (isolation_ratio < pt_ratio_max)

                # Print statements for all variables
                not_isolated_muon_mask = ~isolated_muon_mask
                
                print("isolated_muon_mask")

                print(isolated_muon_mask)

                print("not_isolated_muon_mask")

                print(not_isolated_muon_mask)
                
                # Filter and store the non-isolated muons with the event number (N) and muon id
                if any(not_isolated_muon_mask):

                    # Filter non-isolated muons
                    # We generate a subdataset with only the information from the event muons that are not isolated
                    not_isolated_muons = event_muon[not_isolated_muon_mask].copy()

                    print("not_isolated_muons")
                    print(not_isolated_muons)

                    # Get the index list for non-isolated muons
                    index_list = not_isolated_muons.index.tolist()

                    print("index_list")
                    print(index_list)
                    # Loop through the index list and remove the non-isolated muons from the dataframe
                    #recordar que ix es el numero del evento
                    for index_event in index_list:
                        df_muons = df_muons.drop((ix, index_event))
                                   
            except KeyError:
                #Tenemos solo tracks y no towers
                
                print(f"Evento que tiene solo track'{ix}'")
                
                
                print("event_track")
                print(event_track)

                #print(deltaRcalculation(event_muon, event_track, None))
                delta_r_tracks, delta_r_towers = deltaRcalculation(event_muon, event_track, None)
                
                
                print("delta_r_tracks")
                print(delta_r_tracks)

                print("delta_r_towers")
                print(delta_r_towers)
                
                
                track_pt = event_track['pt'].values
                tower_et = None
                muon_pt = event_muon['pt'].values
                track_pdg = event_track['pdg'].values
                
                isolation_ratio_tracks, isolation_ratio_towers = \
                cone_isolation(track_pt, tower_et, muon_pt, track_pdg, delta_r_tracks, delta_r_towers)

                
                isolation_ratio = isolation_ratio_tracks

                isolated_muon_mask = (isolation_ratio < pt_ratio_max)

                not_isolated_muon_mask = ~isolated_muon_mask

                
                if any(not_isolated_muon_mask):
 
                    not_isolated_muons = event_muon[not_isolated_muon_mask].copy()

                    index_list = not_isolated_muons.index.tolist()

                    for index_event in index_list:
                        df_muons = df_muons.drop((ix, index_event))
                        
                
        except KeyError:
            

            #si no tiene tracks, puede que si tenga towers
            try:
                event_tower = df_towers.loc[ix]
                #event_muon = df_muons.loc[ix]

                print(f"Evento que tiene solo tower'{ix}'")
                
                
                print("event_track")
                print(event_track)

                #print(deltaRcalculation(event_muon, None, event_tower))
                delta_r_tracks, delta_r_towers = deltaRcalculation(event_muon, None, event_tower)
                
                
                print("delta_r_tracks")
                print(delta_r_tracks)

                print("delta_r_towers")
                print(delta_r_towers)
                
                #print("Hola")
                track_pt = None
                tower_et = event_tower['et'].values
                muon_pt = event_muon['pt'].values
                track_pdg = None
                
                #cone_isolation(track_pt, tower_et, muon_pt, delta_r_tracks, delta_r_towers, delta_r_max= 0.2, pt_min = 0.5)
                isolation_ratio_tracks, isolation_ratio_towers = \
                cone_isolation(track_pt, tower_et, muon_pt, track_pdg, delta_r_tracks, delta_r_towers)
                
                #print("Hola 2")
                print("isolation_ratio_tracks")
                print(isolation_ratio_tracks)

                print("isolation_ratio_towers")
                print(isolation_ratio_towers)
                
                isolation_ratio = 0.4 * isolation_ratio_towers

                isolated_muon_mask = (isolation_ratio < pt_ratio_max)

                not_isolated_muon_mask = ~isolated_muon_mask


                print("isolated_muon_mask")

                print(isolated_muon_mask)

                print("not_isolated_muon_mask")

                print(not_isolated_muon_mask)
                
                if any(not_isolated_muon_mask):
 
                    not_isolated_muons = event_muon[not_isolated_muon_mask].copy()

                    index_list = not_isolated_muons.index.tolist()

                    for index_event in index_list:
                        df_muons = df_muons.drop((ix, index_event))
                
            except KeyError:
                #no tiene ninguno de los dos (no elimina nada)
                a = 1
        
    return df_muons

In [62]:
df_muon = muon_isolation(df_muons, df_tracks, df_towers)

Evento que tiene track y tower: '0'
delta_r_tracks
[[ 6.75182795  7.46943062 12.40578368  3.59802567  1.75539674]
 [ 1.74436855  1.36513212  5.44841459  6.90723283  8.47937062]
 [ 6.85948897  7.57033313 12.47736914  3.5144976   1.62209172]
 [ 4.92026374  4.62380699  6.11144312  5.59965242  8.30954611]
 [ 1.30874888  2.14686834  7.64513748  6.61456495  7.16573776]]
within_cone_tracks_int
[[0 0 0 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [1 1 0 0 0]
 [1 1 0 0 0]]
track_filtered antes de evitar la doble cuenta
[[  0.           0.           0.         142.17586902 138.87999004]
 [136.76196627 136.2502274    0.           0.           0.        ]
 [  0.           0.           0.         142.17586902 138.87999004]
 [136.76196627 136.2502274    0.           0.           0.        ]
 [136.76196627 136.2502274    0.           0.           0.        ]]
track_pdg_array
[  13   -2   13 -751   13]
track_pdg_mask
[1 0 1 0 1]
pdg_within_mask
[[10000000000000000 10000000000000000 10000000000000000 10000000000000